name: mars
channels:
  - pytorch
  - defaults
  - conda-forge
  - plotly
dependencies:
  - jupyter
  - pyarrow=4.0.0
  - python=3.8.8
  - pip=21.0.1
  - cudatoolkit=10.2
  - pytorch=1.10.0
  - matplotlib
  - pandas=1.2.4
  - numpy=1.20.3
  - scikit-learn=0.24.2
  - joblib
  - tqdm=4.60.0
  - jsonnet=0.17.0
  - seaborn=0.11.1
  - statsmodels
  - lightgbm=3.1.1
  - shap
  - plotly
  - pdpbox
  - pip:
    - click
    - coloredlogs
    - omegaconf==2.0.5
    - python-dotenv
    - mlflow==1.20.2
    - pytest
    - xgboost
